CC      = x86_64-w64-mingw32-gcc
EMACS   = emacs
CFLAGS  = -std=c99 -Wall -Wextra -O3 -g3
LDFLAGS = -lxinput1_3

joymacs.dll : joymacs.c
	$(CC) -shared -fpic $(LDFLAGS) $(CFLAGS) -o $@ $^ $(LDFLAGS)

joydemo.elc : joydemo.el
	$(EMACS) -Q -batch -L . -f batch-byte-compile $^

run : joydemo.elc joymacs.dll
	$(EMACS) -Q -L . -l $< -f joydemo

clean :
	$(RM) joymacs.so joymacs.dll
